ports:
- port: 8501
  onOpen: open-preview
tasks:
- init: >
    python -m pip install --upgrade pip &&
    python -m pip install -r requirements.txt 
  command: >
    streamlit run ./emmaus_walking/app.py &