ports:
- port: 8501
  onOpen: open-preview
- port: 8888
  onOpen: open-browser

# port 8888 is used by Jupyter - need to work out how to integrate Jupyter properly in gitpod

tasks:
- init: >
    python -m pip install --upgrade pip &&
    python -m pip install -r requirements.txt 
  command: >
    streamlit run ./emmaus_walking/app.py &

