ports:
  - port: 8501
    onOpen: open-browser

tasks:
  - command: python3 -m pip install --upgrade pip
  - command: pip3 install -r requirements.txt
  - command: streamlit run ./emmaus_walking/app.py