baseurl: /emmaus_walking/
collections:
  tooltips:
    output: false
company_name: DataBooth
defaults:
- scope:
    path: ''
    type: pages
  values:
    comments: true
    layout: page
    search: true
    sidebar: home_sidebar
    topnav: topnav
- scope:
    path: ''
    type: tooltips
  values:
    comments: true
    layout: page
    search: true
    tooltip: true
description: App to visualise via mapping my tracked walks
exclude:
- vendor
google_analytics: null
google_search: null
highlighter: rouge
host: 127.0.0.1
kramdown:
  auto_ids: true
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
markdown: kramdown
output: web
permalink: pretty
plugins:
- jekyll-remote-theme
port: 4000
remote_theme: fastai/nbdev-jekyll-theme
repository: mjboothaus/emmaus_walking
sidebars:
- home_sidebar
site_title: emmaus_walking
topnav_title: emmaus_walking
use_math: true
